name: Generate Metrics

on:
  schedule:
    - cron: "0 2 * * *" # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate github-metrics.svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: vian0001
          template: classic
          filename: github-metrics.svg

          base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed

          plugin_lines: yes
          plugin_followup: yes
          config_timezone: Asia/Jakarta
